import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import linear_model
from sklearn import metrics
from sklearn.model_selection import train_test_split
df=pd.read_csv("FuelConsumption.csv")
cdf=df[['ENGINESIZE','CYLINDERS','FUELCONSUMPTION_CITY','FUELCONSUMPTION_HWY','FUELCONSUMPTION_COMB','CO2EMISSIONS']]
plt.scatter(cdf.FUELCONSUMPTION_COMB, cdf.CO2EMISSIONS, color="red")
plt.xlabel("Engine size")
plt.ylabel("CO2 Emissions")
plt.show()
print(cdf.isnull().sum())
cdf.fillna(0,inplace=True)
print(cdf.isnull().sum())
print ("------Simple Linear-------")
x=np.asanyarray(cdf[['ENGINESIZE']])
y=np.asanyarray(cdf[['CO2EMISSIONS']])
xTrain, xTest, yTrain, yTest = train_test_split(x,y,test_size=0.25)
regr=linear_model.LinearRegression()
regr.fit(xTrain,yTrain)
print("Coefficient: ", regr.coef_)
yPredict=regr.predict(xTest)
plt.scatter(xTest,yTest,color="green")
plt.xlabel("Engine size")
plt.ylabel("CO2 Emissions")
plt.plot(xTest,yPredict,color="red")
plt.show()
mse=metrics.mean_squared_error(yTest,yPredict)
print (mse)
variance=regr.score(xTest,yTest)
print (variance)
print ("------Multiple Linear-------")
x=np.asanyarray(cdf[['ENGINESIZE','CYLINDERS','FUELCONSUMPTION_CITY','FUELCONSUMPTION_HWY']])
y=np.asanyarray(cdf[['CO2EMISSIONS']])
xTrain, xTest, yTrain, yTest = train_test_split(x,y,test_size=0.25)
regr=linear_model.LinearRegression()
regr.fit(xTrain,yTrain)
print("Coefficient: ", regr.coef_)
yPredict=regr.predict(xTest)
#plt.scatter(xTest,yTest,color="green")
#plt.xlabel("Engine size")
#plt.ylabel("CO2 Emissions")
#plt.plot(xTest,yPredict,color="red")
#plt.show()
mse=metrics.mean_squared_error(yTest,yPredict)
print (mse)
variance=regr.score(xTest,yTest)
explainedVarScore=metrics.explained_variance_score(yTest,yPredict)
print (explainedVarScore)